// <auto-generated />
using System;
using ES.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ES.DataAccess.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ES.Model.PersonDbDetails", b =>
                {
                    b.Property<Guid>("personId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("fromFloor")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("toFloor")
                        .HasColumnType("tinyint");

                    b.Property<int?>("weight")
                        .HasColumnType("int");

                    b.HasKey("personId");

                    b.ToTable("PersonDbDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
